CREATE TABLE user (
    id int(6) UNSIGNED AUTO_INCREMENT PRIMATY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    message VARCHAR(100) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPSATE CURRENT_TIMESTAMP
)